image: node:18

stages:
  - lint

lint:
  stage: lint
  script:
    - echo "Installing dependencies..."
    - npm install --legacy-peer-deps
    - echo "Running linting..."
    - npm run lint
  allow_failure: false
  except:
    - main
 